### ISSUE TITLE
US02 - Registration

### ISSUE THREAD

**Issue by AlessioBrazerol** [uzh-network-ninjas/ase-social-network#3]
**As a**: new user
**I want**: to be able to register and create a new account with my username, email, password
**So that**: I can log into my account

## Development tasks
- [x] #57 
- [x] #65

**Comment by AlessioBrazerol** [comment]
@maettuu will you implement any restrictions on the password in the backend? e.g., non-empty, min length, etc.

**Comment by AlessioBrazerol** [comment]
@maettuu In the case of HTTP Status Code 409 Conflict, I need to know if the registration request failed because the username was already taken or the email. 
Thus we most likely need something like internal error codes that we can send with the response body, something like ProblemDetail in Spring Boot. For example:
`{
code: 1,
message: "Username already taken",
timestamp: xxxx
}`
What do you think? Or do you have a better idea?

**Comment by maettuu** [comment]
@AlessioBrazerol are you using username or email for registration/login?

**Comment by AlessioBrazerol** [comment]
> @AlessioBrazerol are you using username or email for registration/login?

For registration email and username. We decided to remove profilename from registration. (we need to discuss in the weekly if we still use it as an optional field that can be set in the profile settings, like github)
You can choose if you want to support login with only username, only email or dynamically switch depending on what is provided.
